module.exports = {
	connection: 'mysql',
	migrate: 'safe',
	tableName: 'Payments',
	tableNameSqlServer: 'OVPM',
	attributes: {
		DocEntry:{type:'integer'},
		DocNum:{type:'integer'},
		DocType:{type:'string',size:1},
		Canceled:{type:'string',size:1},
		Handwrtten:{type:'string',size:1},
		Printed:{type:'string',size:1},
		DocDate:{type:'datetime'},
		DocDueDate:{type:'datetime'},
		CardCode:{type:'string',size:15},
		CardName:{type:'string',size:100},
		Address:{type:'string',size:254},
		DdctPrcnt:{type:'float'},
		DdctSum:{type:'float'},
		DocTotal:{type:'float'},
		DocTotalFC:{type:'float'},
		Comments:{type:'string',size:254},
		JrnlMemo:{type:'string',size:50},
		TransId: {type:'integer'},
		UpdateDate: {type:'datetime'},
		CreateDate: {type:'datetime'},
		TaxDate: {type:'datetime'},
		Confirmed: {type:'strig',size:1},
		PayToCode: {type:'strig',size:50},
		CancelDate: {type:'datetime'},
		U_UUID:{type:'string',size:50},
		U_SAT_SERIECFD:{type:'string',size:20},
		U_SAT_FPAGO:{type:'string',size:30},
		U_SAT_BENEFICIARIO:{type:'string',size:100},
		U_SAT_LICTRADNUM:{type:'string',size:13}
	},

}